# ***************************生产配置**************************** #
spring:
  redis:
    cluster:
      max-redirects: 3
      nodes: 10.0.0.8:21006,10.0.0.8:21007,10.0.0.8:21008,10.0.0.8:21009,10.0.0.8:21010,10.0.0.8:21011
    password: platscan
# 应用版本
version: 0.7.0
# 当前激活的配置名称(请不要修改)
profile: prod
# 服务器端口号
port: 38030
# MySQL数据库连接地址
dburl: jdbc:mysql://52.187.38.88:3306/platon_browser_${version}?useUnicode=true&characterEncoding=utf-8&useSSL=false
dbuser: root
dbpass: Juzhenyuan_123
# 日志文件存储文件
logpath: /data/logs/${spring.application.name}-${version}-${profile}.log
# 日志级别
loglevel:
  spring: error
  platon: error

#初始化链相关的配置
platon.config:
  # 质押节点统计年化率最多取多少个连续周期
  maxSettlePeriodCount4AnnualizedRateStat: 4
  #PlatON初始总发行量(LAT)
  initIssueAmount: 10000000000
  #每年固定增发比例
  addIssueRate: 0.025
  #每年增发分配给激励池的比例
  incentiveRateFromIssue: 0.8
  #每个共识轮中回退多少个块是选举下一轮验证人的时机
  electionBackwardBlockCount: 20
  #开发者激励基金账户地址
  developerIncentiveFundAccountAddr: '0x60ceca9c1290ee56b98d4e160ef0453f7c40d219'
  #PlatOn基金会账户地址
  platonFundAccountAddr: '0x493301712671ada506ba6ca7891f436d29185821'
  #10年内基金会向激励池填充额度: <第几年-补贴金额(LAT)>
  foundationSubsidies: {
    '1':62215742.4869165,
    '2':55965742.4869165,
    '3':49559492.4869165,
    '4':42993086.2369165,
    '5':36262519.8306666,
    '6':29363689.2642633,
    '7':22292387.9336939,
    '8':15044304.0698633,
    '9':7615018.1094369
  }
  # 初始内置节点默认质押金额(LAT)
  defaultStakingLockedAmount: 10000000
  #提案url参数模板
  proposalUrlTemplate: https://github.com/PlatONnetwork/PIPs/github/blob/master/PIPs/PIP-{pip_id}.md
  #keysBase网址
  keyBase: https://keybase.io/

brokenHost: 192.168.16.173
brokenPort: 61613
system.username: admin
system.password: admin
client.username: guest
client.password: guest
