# ***************************开发配置**************************** #
# 应用版本
version: 0.7.0
# 当前激活的配置名称(请不要修改)
profile: dev
# 服务器端口号
port: 9061
# MySQL数据库连接地址
dburl: jdbc:mysql://192.168.9.191:3306/platon_browser_${version}_${profile}?useUnicode=true&characterEncoding=utf-8&useSSL=false
dbuser: platon
dbpass: platon
# Platon链配置,格式【{chainName1}-{chainId1}-{http://nodeIP1:port1}[,{chainName2}-{chainId2}-{http://nodeIP2:port2}]】，多个链配置使用逗号分隔
#chain.config: MAIN_NET-1-http://192.168.9.76:8793
#chain.config: MAIN_NET-1-http://10.10.8.151:7793
chain.config: MAIN_NET-203-["http://192.168.120.81:6789","http://192.168.120.82:6789","http://192.168.120.83:6789","http://192.168.120.84:6789"]
#chain.config: MAIN_NET-1-https://syde.platon.network/test
# Redis集群节点
redis: 192.168.9.191:7001,192.168.9.191:7002,192.168.9.191:7003,192.168.9.191:7004,192.168.9.191:7005,192.168.9.191:7006
# 日志文件存储文件
logpath: ./logs/${spring.application.name}-${version}-${profile}.log
# 日志级别
loglevel:
  spring: debug
  platon: debug
web3j:
  addresses: http://192.168.9.221:6789
brokenHost: 192.168.16.173  
brokenPort: 61613
system.username: admin
system.password: admin
client.username: guest
client.password: guest