# ***************************测试配置**************************** #
# 应用版本
version: 0.7.4.0
# 当前激活的配置名称(请不要修改)
profile: dev
# 密码加密配置
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}
# 服务器端口号
server.port: 9061
#Spring框架内部配置
spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://192.168.9.191:3306/platon_browser_${version}_${profile}?useUnicode=true&characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    username: ENC(fCJq964pYDHTpeHbiJR8fw==)
    password: ENC(fCJq964pYDHTpeHbiJR8fw==)
  #ES配置
  elasticsearch:
    high-level-client:
      hosts: 192.168.120.103,192.168.120.104,192.168.120.105
      port: 9200
      schema: http
      blockIndexName: browser_block_1
      transactionIndexName: browser_transaction_1
      delegationIndexName: browser_delegation_1
      nodeOptIndexName: browser_nodeopt_1
#redis配置
redisCluster:
  configKey: DEFAULT
  connectionTimeout: 4000
  soTimeout: 5000
  maxRedirections: 3000
  maxTotal: 10
  maxIdle: 5
  minIdle: 2
  maxWaitMillis: 2000
  testOnBorrow: false
  testOnReturn: false
  testWhileIdle: true
  masterIPs: 192.168.9.191:7001,192.168.9.191:7002,192.168.9.191:7003,192.168.9.191:7004,192.168.9.191:7005,192.168.9.191:7006
  password: platscan
#性能配置
server:
  tomcat:
    max-connections: 20000
    min-spare-threads: 800
    max-threads: 2000
  connection-timeout: 5000
zuul:
  FormBodyWrapperFilter:
    pre:
     disable: true
#日志配置
logging:
  file: ./logs/${spring.application.name}-${version}-${profile}.log
  #日志级别
  level:
    org.springframework: debug
    com.platon.browser: debug
    com.platon.browser.service: debug
    com.platon.browser.task: debug
    com.platon.browser.client: debug
    com.platon.browser.dao: debug
#初始化链相关的配置
platon:
  # 交易输入参数并行解码线程数
  txLogDecodeThreadNum: 200
  # Web3j访问地址
  web3j:
    #HTTP或WS
    protocol: HTTP
    addresses: 192.168.112.171:6789
  # 质押节点统计年化率最多取多少个连续周期
  maxSettlePeriodCount4AnnualizedRateStat: 4
  #PlatON初始总发行量(LAT)
  initIssueAmount: 10000000000
  #每年固定增发比例
  addIssueRate: 0.025
  #每年增发分配给激励池的比例
  incentiveRateFromIssue: 0.8
  #每个共识轮中回退多少个块是选举下一轮验证人的时机
  electionBackwardBlockCount: 20
  #10年内基金会向激励池填充额度: <第几年-补贴金额(LAT)>
  foundationSubsidies: {
    '1':62215742.4869165,
    '2':55965742.4869165,
    '3':49559492.4869165,
    '4':42993086.2369165,
    '5':36262519.8306666,
    '6':29363689.2642633,
    '7':22292387.9336939,
    '8':15044304.0698633,
    '9':7615018.1094369
  }
  # 初始内置节点默认质押金额(LAT)
  defaultStakingLockedAmount: 10000000
  #提案url参数模板
  proposalUrlTemplate: https://github.com/PlatONnetwork/PIPs/github/blob/master/PIPs/PIP-{pip_id}.md
  #keysBase网址
  keyBase: https://keybase.io/
  #keyBase api
  keyBaseApi: _/api/1.0/user/autocomplete.json?q=


brokenHost: 192.168.16.173
brokenPort: 61613
system.username: admin
system.password: admin
client.username: guest
client.password: guest
