# ***************************通用配置: 请不要修改此文件，此文件由模板自动生成，若要修改，请移步至conftpl目录**************************** #
# 应用版本
version: 1.0.0.0
#服务器配置
server:
  servlet:
    context-path: /browser-server
#Spring应用配置
spring:
  profiles.active: test
  application.name: browser-api
  session.timeout: 1800  #以秒为单位
  #国际化配置
  messages.basename: messages
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  #Redis键配置
  redis:
    key:
      #最多存储多少条数据
      max-item: 500000
      #区块列表
      blocks: browser:${profile}:blocks
      #交易列表
      transactions: browser:${profile}:transactions
      #统计信息
      networkStat: browser:${profile}:networkStat
      #内部转账交易
      transferTx: browser:${profile}:transferTx
      #erc20交易
      erc20Tx: browser:${profile}:erc20Tx
      #erc721交易
      erc721Tx: browser:${profile}:erc721Tx
  #ES索引配置
  elasticsearch:
    index:
      blockIndexName: browser_block_${profile}
      transactionIndexName: browser_transaction_${profile}
      delegationIndexName: browser_delegation_${profile}
      nodeOptIndexName: browser_nodeopt_${profile}
      delegationRewardIndexName: browser_delegation_reward_${profile}
      transferTxIndexName: browser_transfer_tx_${profile}
      erc20TxIndexName: browser_erc20_tx_${profile}
      erc721TxIndexName: browser_erc721_tx_${profile}
# MyBatis配置（注意：一定要对应mapper映射xml文件的所在路径）
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  # 实体类别名配置（注意：对应实体类的路径）
  type-aliases-package: com.platon.browser.dao.entity

