# ***************************测试配置**************************** #
# 当前激活的配置名称(请不要修改)
profile: dev
# 密码加密配置
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}
# 服务器端口号
server.port: 9061
#Spring框架内部配置
spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/browser_0.13.5.0_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: root
  #ES配置
  elasticsearch:
    high-level-client:
      hosts: 192.168.120.103,192.168.120.104,192.168.120.105
      port: 9200
      schema: http
      username: elastic
      password: changeme
      blockIndexName: browser_block_local
      transactionIndexName: browser_transaction_local
      delegationIndexName: browser_delegation_local
      nodeOptIndexName: browser_nodeopt_local
      delegationRewardIndexName: browser_delegation_reward_local
      innerTxIndexName: browser_inner_tx_local
#redis配置
redisCluster:
  configKey: DEFAULT
  connectionTimeout: 4000
  soTimeout: 5000
  maxRedirections: 3000
  maxTotal: 10
  maxIdle: 5
  minIdle: 2
  maxWaitMillis: 2000
  testOnBorrow: false
  testOnReturn: false
  testWhileIdle: true
  masterIPs: 192.168.16.171:7000,192.168.16.171:7001,192.168.16.171:7002,192.168.16.172:7000,192.168.16.172:7001,192.168.16.172:7002
  password: platscan
#性能配置
server:
  tomcat:
    max-connections: 20000
    min-spare-threads: 800
    max-threads: 2000
  connection-timeout: 5000
zuul:
  FormBodyWrapperFilter:
    pre:
     disable: true
#日志配置
logging:
  file: ./logs/${spring.application.name}-${version}-${profile}.log
  #日志级别
  level:
    org.springframework: debug
    com.platon.browser: debug
    com.platon.browser.service: debug
    com.platon.browser.task: debug
    com.platon.browser.client: debug
    com.platon.browser.dao: debug
#初始化链相关的配置
platon:
  # 交易输入参数并行解码线程数
  txLogDecodeThreadNum: 200
  # Web3j访问地址
  web3j:
    #HTTP或WS
    protocol: HTTP
    addresses: 192.168.112.172:6778
  # 质押节点统计年化率最多取多少个连续周期
  maxSettlePeriodCount4AnnualizedRateStat: 4
  #PlatON初始总发行量(ATP)
  initIssueAmount: 100000000
  #每年固定增发比例
  addIssueRate: 0.05
  #每年增发分配给激励池的比例
  incentiveRateFromIssue: 0.4
  #每个共识轮中回退多少个块是选举下一轮验证人的时机
  electionBackwardBlockCount: 20
  #10年内计算士基金会向激励池填充额度: <第几年-补贴金额(ATP)>
  foundationSubsidies: {
    '1':0,
    '2':0,
    '3':0,
    '4':0,
    '5':0,
    '6':0,
    '7':0,
    '8':0,
    '9':0
  }
  # 初始内置节点默认质押金额(ATP)
  defaultStakingLockedAmount: 10500
  #区块最大Gas限制
  maxBlockGasLimit: 100800000
  #提案url参数模板
  proposalUrlTemplate: https://github.com/PlatONnetwork/PIPs/github/blob/master/PIPs/PIP-{pip_id}.md
  #keysBase网址
  keyBase: https://keybase.io/
  #keyBase api
  keyBaseApi: _/api/1.0/user/lookup.json?key_suffix=
  #链id
  chainId: 201018

recaptchaUrl: https://recaptcha.net/recaptcha/api/siteverify?secret=6Lf8KLcUAAAAAPyHZfa7oeWjdMSyvgDHUUeYf01Z&response=%s
isRecaptcha: false
limit:
  num: 10
output:
  file:
    url: D:/