# ***************************通用配置**************************** #

#服务器配置
server:
  port: ${port}
  servlet:
    context-path: /browser-server
#Spring应用配置
spring:
  profiles.active: dev
  application.name: browser-api
  #国际化配置
  messages.basename: messages
  #Redis集群配置
  redis:
    database: 0
    cluster:
      max-redirects: 3
      nodes: ${redis}
  #数据源配置
  datasource:
    name: test
    url: ${dburl}
    username: ${dbuser}
    password: ${dbpass}
    #druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name: com.mysql.jdbc.Driver
# Platon配置
platon:
  web3j:
    addresses: ${web3j.addresses}
    collect.batch-size: ${web3j.collect.batch-size}

  fake.location.filename: fakelocation-${version}-${profile}.json
  # 区块列表缓存和交易列表缓存配置
  redis:
    key:
      #验证节点列表
      node: browser:${profile}:nodes
      #节点ID与其所出最大块号的映射
      nodeid-maxblocknum: browser:${profile}:nodeid-maxblocknum:{nodeId}
      #区块列表
      block: browser:${profile}:blocks
      #交易列表
      transaction: browser:${profile}:transactions
      #统计信息
      networkStat: browser:${profile}:networkStat
      #总交易笔数
      trans-count: browser:${profile}:trans-count
      #24小时内的交易数
      trans-count-24-hours: browser:${profile}:trans-count-24-hours
      #地址数
      address-count: browser:${profile}:address-count
      #平均区块交易数
      avg-block-trans-count: browser:${profile}:avg-block-trans-count
      #票价
      ticket-price: browser:${profile}:ticket-price
      #投票数
      vote-count: browser:${profile}:vote-count
      #MaxTps
      max-tps: browser:${profile}:max-tps
      # 按地址存储的交易的键模板
      address-trans-key-template: browser:${profile}:address-trans-list:{address}:{txType}:{txHash}:{timestamp}
      # 按地址存储的交易数量限制
      address-trans-max-item: 200
    max-item: 500000
#日志配置
logging:
  file: ${logpath}
  level:
    org.springframework: ${loglevel.spring}
    com.platon.browser: ${loglevel.platon}

# MyBatis配置（注意：一定要对应mapper映射xml文件的所在路径）
mybatis:
  mapper-locations: classpath:mapper/*.xml
  # 实体类别名配置（注意：对应实体类的路径）
  type-aliases-package: com.platon.browser.dao.entity
