# ***************************测试配置**************************** #
# 应用版本
version: 0.6.0
# 当前激活的配置名称(请不要修改)
profile: amigo
# 服务器端口号
port: 28060
# MySQL数据库连接地址
dburl: jdbc:mysql://127.0.0.1:3306/platon_browser_${version}_${profile}?useUnicode=true&characterEncoding=utf-8&useSSL=false
dbuser: juzix
dbpass: Juzhen123!
# Platon链配置,格式【{chainName1}-{chainId1}-{http://nodeIP1:port1}[,{chainName2}-{chainId2}-{http://nodeIP2:port2}]】，多个链配置使用逗号分隔
chain.config: MAIN_NET-103-["http://127.0.0.1:6790","http://13.67.44.50:6791","http://13.67.44.50:6792"]
# Redis集群节点
redis: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005,127.0.0.1:7006
# 日志文件存储文件
logpath: /opt/console/logs/${spring.application.name}-${version}-${profile}.log
# 日志级别
loglevel:
  spring: error
  platon: error