# ***************************Aton测试配置**************************** #
# 当前激活的配置名称(请不要修改)
profile: press
# 密码加密配置
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}
#Spring框架内部配置
spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://10.1.1.54:3306/platon_browser?useUnicode=true&characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: ENC(WdsbLfMqOVt4fifwvlrP/g==)
    password: ENC(YAS0fQLf2HgpNwy8EosToc3pBFUyvsla)
  #Redis配置
  redis:
    cluster:
      max-redirects: 3
      nodes: 10.1.1.55:6379,10.1.1.55:6380,10.1.1.56:6379,10.1.1.56:6380,10.1.1.57:6380,10.1.1.57:6379
    password: 4Fz+gV4ypvWH4gDEb
  #ES配置
  elasticsearch:
    high-level-client:
      hosts: 10.1.1.55,10.1.1.56,10.1.1.57
      port: 9200
      schema: http
      username: elastic
      password: changeme
      delegationIndexName: browser_delegation_${profile}
      blockIndexName: browser_block_${profile}
      transactionIndexName: browser_transaction_${profile}
      nodeOptIndexName: browser_nodeopt_${profile}
      delegationRewardIndexName: browser_delegation_reward_${profile}
#日志配置
logging:
  file: ./logs/${spring.application.name}-${version}-${profile}.log
  #日志级别
  level:
    org.springframework: error
    org.springframework.retry: error
#同步时的索引查询分页参数配置
paging:
  block:
    pageSize: 2000
    pageCount: 250
  transaction:
    pageSize: 2000
    pageCount: 250
disruptor:
  queue:
    block:
      buffer-size: 1024
      batch-size: 1024
    transaction:
      buffer-size: 1024
      batch-size: 8192
    nodeopt:
      buffer-size: 1024
      batch-size: 1024
    node:
      buffer-size: 1024
      batch-size: 3
    stake:
      buffer-size: 1024
      batch-size: 3
    delegation:
      buffer-size: 1024
      batch-size: 1024
    proposal:
      buffer-size: 1024
      batch-size: 3
    vote:
      buffer-size: 1024
      batch-size: 3
    rpplan:
      buffer-size: 1024
      batch-size: 3
    estimate:
      buffer-size: 1024
      batch-size: 1024
    reward:
      buffer-size: 1024
      batch-size: 1024
    slash:
      buffer-size: 1024
      batch-size: 3
    address:
      buffer-size: 1024
      batch-size: 1024
#PlatOn相关配置
platon:
  # 交易输入参数并行解码线程数
  txLogDecodeThreadNum: 10
  # Web3j访问地址
  web3j:
    #HTTP或WS
    protocol: WS
    addresses: 192.168.112.172:8788
  # 质押节点统计年化率最多取多少个连续周期
  maxSettlePeriodCount4AnnualizedRateStat: 4
  #PlatON初始总发行量(LAT)
  initIssueAmount: 10000000000
  #每年固定增发比例
  addIssueRate: 0.025
  #每年增发分配给激励池的比例
  incentiveRateFromIssue: 0.8
  #每个共识轮中回退多少个块是选举下一轮验证人的时机
  electionBackwardBlockCount: 20
  #10年内基金会向激励池填充额度: <第几年-补贴金额(LAT)>
  foundationSubsidies: {
    '1':62215742,
    '2':55965742,
    '3':49559492,
    '4':42993086,
    '5':36262520,
    '6':29363689,
    '7':22292388,
    '8':15044304,
    '9':7615018
  }
  # 初始内置节点默认质押金额(LAT)
  defaultStakingLockedAmount: 1500000
  #区块最大Gas限制
  maxBlockGasLimit: 100800000
  #提案url参数模板
  proposalUrlTemplate: https://github.com/danielgogo/PIPs/blob/master/PIP-%s.md
  #提案pip_num参数模板
  proposalPipNumTemplate: PIP-%s
  #keysBase网址
  keyBase: https://keybase.io/
  #keyBase api
  keyBaseApi: _/api/1.0/user/autocomplete.json?q=
    #链id
  chainId: 108
  # 地址重复使用的最大次数
  addressReusedTimes: 50
  #节点条数
  nodeMaxCount: 600
  #质押条数
  stakeMaxCount: 1200
  #委托条数
  delegateMaxCount: 1000000
  #提案条数
  proposalMaxCount: 600
  #投票最大条数
  voteMaxCount: 6000
  #rpplan最大条数
  rpplanMaxCount: 6000
  #slash最大条数
  slashMaxCount: 600
  #地址最大条数
  addressMaxCount: 1500000
  #区块最大条数
  blockMaxCount: 28799250
  #日志最大条数
  nodeoptMaxCount: 1788000
  #每个区块的交易数
  txCountPerBlock: 100
  #每个委托奖励数
  rewardMaxCount: 2000000
  #gas 数据
  estimateMaxCount: 1000000
