# ***************************开发配置**************************** #
#服务器配置
server.port: 8080
#Spring应用配置
spring.redis.cluster.nodes: 192.168.18.9:21006,192.168.18.9:21007,192.168.18.9:21008,192.168.18.9:21009,192.168.18.9:21010,192.168.18.9:21011
#数据源配置
datasource:
  url: jdbc:mysql://localhost:3306/platon_browser_0.4.0?useUnicode=true&characterEncoding=utf-8&useSSL=false
  username: root
  password: root
#日志配置
logging:
  file: ./server-dev.log
  level:
    org:
      springframework:
        boot: debug
        web: debug
        jdbc: debug
        dao: debug
        transaction: debug
      mybatis: debug
    com.platon.browser.dao: debug

platon:
  # 链配置格式 链名称:链ID，多个链配置使用逗号分隔
  chains: MAIN_NET:1
  # 区块列表缓存和交易列表缓存配置
  redis:
    key:
      node: browser:0.4.0:dev:chain{}:nodes
      push-node: browser:0.4.0:dev:chain{}:pushnodes
      block: browser:0.4.0:dev:chain{}:blocks
      transaction: browser:0.4.0:dev:chain{}:transactions
      maxtps: browser:0.4.0:dev:chain{}:maxtps
      max-item: 500000
  # 图片服务器地址
  image.server.url: http://192.168.9.86:8082/