# ***************************_DESCRIPTION_**************************** #
# 应用版本
version: _VERSION_
spring:
  application.name: browser-agent
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  #Redis键配置
  redis:
    key:
      #最多存储多少条数据
      max-item: 500000
      #区块列表
      blocks: browser_${profile}:blocks
      #交易列表
      transactions: browser_${profile}:transactions
      #统计信息
      networkStat: browser_${profile}:networkStat
      #内部转账交易
      transferTx: browser_${profile}:transferTx
      #erc20交易
      erc20Tx: browser_${profile}:erc20Tx
      #erc721交易
      erc721Tx: browser_${profile}:erc721Tx
  #ES索引配置
  elasticsearch:
    index:
      blockIndexName: browser_block_${profile}
      transactionIndexName: browser_transaction_${profile}
      delegationIndexName: browser_delegation_${profile}
      nodeOptIndexName: browser_nodeopt_${profile}
      delegationRewardIndexName: browser_delegation_reward_${profile}
      transferTxIndexName: browser_transfer_tx_${profile}
      erc20TxIndexName: browser_erc20_tx_${profile}
      erc721TxIndexName: browser_erc721_tx_${profile}
# MyBatis配置（注意：一定要对应mapper映射xml文件的所在路径）
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  # 实体类别名配置（注意：对应实体类的路径）
  type-aliases-package: com.platon.browser.dao.entity

task:
   #地址统计任务
   address-batch-size: 1000  