# ***************************_DESCRIPTION_**************************** #
# 应用版本
version: _VERSION_
spring:
  application.name: browser-agent
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
# MyBatis配置（注意：一定要对应mapper映射xml文件的所在路径）
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  # 实体类别名配置（注意：对应实体类的路径）
  type-aliases-package: com.platon.browser.dao.entity

task:
   #地址统计任务
   address-batch-size: 1000  