# ***************************通用配置**************************** #

#Spring应用配置
spring:
  profiles.active: dev
  application.name: browser-agent
  #Redis集群配置
  redis:
    database: 0
    cluster:
      max-redirects: 3
      nodes: ${redis}
  #数据源配置
  datasource:
    name: test
    url: ${dburl}
    username: platon
    password: platon
    #druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name: com.mysql.jdbc.Driver
# Platon配置
platon:
  chain:
    config: ${chain.config}
    active: ${chain.active}
  # 虚假节点位置配置文件
  fake.location.filename: fakelocation.json
  # 批量采集线程池大小
  block.pool.size: ${thread.num}
  # 批量处理数量
  block.batch.num: ${batch.num}
  # 区块列表缓存和交易列表缓存配置
  redis:
    key:
      node: browser:${version}:${profile}:chain{}:nodes
      block: browser:${version}:${profile}:chain{}:blocks
      transaction: browser:${version}:${profile}:chain{}:transactions
      staticstics: browser:${version}:${profile}:chain{}:staticstics
    max-item: 500000
#日志配置
logging:
  file: ${logpath}
  level:
    org.springframework: ${loglevel.spring}
    com.platon.browser: ${loglevel.platon}
    com.platon.browser.job: ${loglevel.platon.job}
    com.platon.browser.filter: ${loglevel.platon.filter}

# MyBatis配置（注意：一定要对应mapper映射xml文件的所在路径）
mybatis:
  mapper-locations: classpath:mapper/*.xml
  # 实体类别名配置（注意：对应实体类的路径）
  type-aliases-package: com.platon.browser.dao.entity

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
