# ***************************开发配置**************************** #
# 当前激活的配置名称(请不要修改)
profile: testdelete
# 密码加密配置
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}
#Spring框架内部配置
spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://192.168.16.171:3306/platon_browser_${version}_${profile}?useUnicode=true&characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: ENC(WdsbLfMqOVt4fifwvlrP/g==)
    password: ENC(YAS0fQLf2HgpNwy8EosToc3pBFUyvsla)
  #Redis配置
  redis:
    cluster:
      max-redirects: 3
      nodes: 192.168.16.171:7000,192.168.16.171:7001,192.168.16.171:7002,192.168.16.172:7000,192.168.16.172:7001,192.168.16.172:7002
    password: platscan
  #ES配置
  elasticsearch:
    high-level-client:
      hosts: 192.168.120.103,192.168.120.104,192.168.120.105
      port: 9200
      schema: http
      username: elastic
      password: changeme
      blockIndexName: browser_block_testdelete
      transactionIndexName: browser_transaction_testdelete
      delegationIndexName: browser_delegation_testdelete
      nodeOptIndexName: browser_nodeopt_testdelete
      delegationRewardIndexName: browser_delegation_reward_testdelete
      innerTxIndexName: browser_inner_tx_testdelete
# 内存环形缓冲区大小，必须是2的指数倍
disruptor:
  queue:
    # 区块事件环形缓冲区大小
    block.buffer-size: 1024
    # 采集事件环形缓冲区大小
    collection.buffer-size: 1024
    # 数据补充环形缓冲区大小
    complement.buffer-size: 1024
    # gas price估算消息环形缓冲区大小
    gasestimate.buffer-size: 1024
    # 数据持久化
    persistence:
      #环形缓冲区大小
      buffer-size: 1024
      #每次处理多少个
      batch-size: 10
#日志配置
logging:
  file: ./logs/${spring.application.name}-${version}-${profile}.log
  #日志级别
  level:
    org.springframework: error
    org.springframework.retry: error
    com.platon.browser: error
    com.platon.browser.bootstrap: error
    com.platon.browser.collection: error
    com.platon.browser.collection.queue.handler: error
    com.platon.browser.common: error
    com.platon.browser.complement: error
    com.platon.browser.complement.handler: error
    com.platon.browser.complement.converter: error
    com.platon.browser.persistence: error
    com.platon.browser.persistence.handler: error
    com.platon.browser.persistence.queue.handler: error
    com.platon.browser.task: error
#PlatOn相关配置
platon:
  # 交易输入参数并行解码线程数
  txLogDecodeThreadNum: 200
  # Web3j访问地址
  web3j:
    #HTTP或WS
    protocol: HTTP
    addresses: 192.168.120.151:6789,192.168.120.151:6790
  # 质押节点统计年化率最多取多少个连续周期
  maxSettlePeriodCount4AnnualizedRateStat: 4
  #PlatON初始总发行量(ATP)
  initIssueAmount: 100000000
  #每年固定增发比例
  addIssueRate: 0.05
  #每年增发分配给激励池的比例
  incentiveRateFromIssue: 0.4
  #每个共识轮中回退多少个块是选举下一轮验证人的时机
  electionBackwardBlockCount: 20
  #10年内计算士基金会向激励池填充额度: <第几年-补贴金额(ATP)>
  foundationSubsidies: {
    '1':0,
    '2':0,
    '3':0,
    '4':0,
    '5':0,
    '6':0,
    '7':0,
    '8':0,
    '9':0
  }
  # 初始内置节点默认质押金额(ATP)
  defaultStakingLockedAmount: 10500
  #区块最大Gas限制
  maxBlockGasLimit: 100800000
  #提案url参数模板
  proposalUrlTemplate: https://github.com/danielgogo/PIPs/blob/master/PIP-%s.md
  #提案pip_num参数模板
  proposalPipNumTemplate: PIP-%s
  #keysBase网址
  keyBase: https://keybase.io/
  #keyBase api
  keyBaseApi: _/api/1.0/user/autocomplete.json?q=
  #链id
  chainId: 201018
  #锁仓最小释放金额参数生效版本
  restrictingMinimumReleaseActiveVersion:
  #最小锁仓释放金额(VON)  M值的治理范围：主网：默认值500 lat [500, 10000000] / Alaya：默认值80 atp [80, 100000]
  restrictingMinimumRelease: 80000000000000000000
  #锁仓释放金额范围(VON)
  restrictingMinimumReleaseRange: '[80000000000000000000, 100000000000000000000000]'

task:
  #地址统计任务
  address-batch-size: 1000
  #动态调整参数
  dynamic-adjust:
    #agent与实际链上区块号相差多少个块号时触发调整操作
    threshold: 20
    #未追上链,批量入ES和Redis的缓存大小
    cache-batch-max-size: 10
    #已追上链,批量入ES和Redis的缓存大小
    cache-batch-min-size: 1