# ***************************Aton开发配置**************************** #
# 应用版本
version: 0.7.3.1
# 当前激活的配置名称(请不要修改)
profile: dev
# 密码加密配置
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}
#Spring框架内部配置
spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://192.168.16.171:3306/platon_browser_${version}_${profile}?useUnicode=true&characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: ENC(bpshgjWOgn2d+oGmSTBPNA==)
    password: ENC(bpshgjWOgn2d+oGmSTBPNA==)
  #Redis配置
  redis:
    cluster:
      max-redirects: 3
      nodes: 192.168.9.191:7001,192.168.9.191:7002,192.168.9.191:7003,192.168.9.191:7004,192.168.9.191:7005,192.168.9.191:7006
    password: platscan
  #ES配置
  elasticsearch:
    high-level-client:
      hosts: 192.168.120.103,192.168.120.104,192.168.120.105
      port: 9200
      schema: http
      blockIndexName: browser_block_1
      transactionIndexName: browser_transaction_1
      delegationIndexName: browser_delegation_1
      nodeOptIndexName: browser_nodeopt_1
# 内存环形缓冲区大小，必须是2的指数倍
disruptor:
  queue:
    # 区块事件环形缓冲区大小
    block.buffer-size: 1024
    # 采集事件环形缓冲区大小
    collection.buffer-size: 1024
    # 数据补充环形缓冲区大小
    complement.buffer-size: 1024
    # 数据持久化
    persistence:
      #环形缓冲区大小
      buffer-size: 1024
      #每次处理多少个
      batch-size: 10
#日志配置
logging:
  file: ./logs/${spring.application.name}-${version}-${profile}.log
  #日志级别
  level:
    org.springframework: error
    org.springframework.retry: error
    com.platon.browser: error
    com.platon.browser.bootstrap: error
    com.platon.browser.collection: error
    com.platon.browser.collection.queue.handler: error
    com.platon.browser.common: error
    com.platon.browser.complement: error
    com.platon.browser.complement.handler: error
    com.platon.browser.complement.converter: error
    com.platon.browser.persistence: error
    com.platon.browser.persistence.handler: error
    com.platon.browser.persistence.queue.handler: error
    com.platon.browser.task: error
#PlatOn相关配置
platon:
  # Web3j访问地址
  web3j.addresses: http://192.168.120.76:6797
  # 质押节点统计年化率最多取多少个连续周期
  maxSettlePeriodCount4AnnualizedRateStat: 4
  #PlatON初始总发行量(LAT)
  initIssueAmount: 10000000000
  #每年固定增发比例
  addIssueRate: 0.025
  #每年增发分配给激励池的比例
  incentiveRateFromIssue: 0.8
  #每个共识轮中回退多少个块是选举下一轮验证人的时机
  electionBackwardBlockCount: 20
  #10年内计算士基金会向激励池填充额度: <第几年-补贴金额(LAT)>
  foundationSubsidies: {
    '1':62215742,
    '2':55965742,
    '3':49559492,
    '4':42993086,
    '5':36262520,
    '6':29363689,
    '7':22292388,
    '8':15044304,
    '9':7615018
  }
  # 初始内置节点默认质押金额(LAT)
  defaultStakingLockedAmount: 1500000
  #提案url参数模板
  proposalUrlTemplate: https://github.com/danielgogo/PIPs/PIP-%s.md
  #提案pip_num参数模板
  proposalPipNumTemplate: PIP-%s
  #keysBase网址
  keyBase: https://keybase.io/
  #keyBase api
  keyBaseApi: _/api/1.0/user/autocomplete.json?q=