# ***************************通用配置**************************** #

#Spring应用配置
spring:
  profiles.active: test
  application.name: browser-agent
  #Redis集群配置
  redis:
    database: 0
    cluster:
      max-redirects: 3
      nodes: ${redis}
  #数据源配置
  datasource:
    name: test
    url: ${dburl}
    username: ${dbuser}
    password: ${dbpass}
    #druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name: com.mysql.jdbc.Driver
# Platon配置
platon:
  web3j:
    addresses: ${web3j.addresses}
    collect.batch-size: ${web3j.collect.batch-size}
  # 虚假节点位置配置文件
  fake.location.filename: fakelocation.json
  # Redis缓存配置
  redis:
    key:
      #区块列表
      blocks: browser:${version}:${profile}:blocks
      #交易列表
      transactions: browser:${version}:${profile}:transactions
      #统计信息
      networkStat: browser:${version}:${profile}:networkStat
    max-item: 500000
#日志配置
logging:
  file: ${logpath}
  level:
    org.springframework: ${loglevel.spring}
    com.platon.browser: ${loglevel.platon}
    com.platon.browser.service: ${loglevel.platon.service}
    com.platon.browser.task: ${loglevel.platon.task}
    com.platon.browser.engine: ${loglevel.platon.engine}
    com.platon.browser.client: ${loglevel.platon.client}
    com.platon.browser.dao: ${loglevel.platon.dao}

# MyBatis配置（注意：一定要对应mapper映射xml文件的所在路径）
mybatis:
  mapper-locations: classpath:mapper/*.xml
  # 实体类别名配置（注意：对应实体类的路径）
  type-aliases-package: com.platon.browser.dao.entity
