# ***************************开发配置**************************** #
# 应用版本
version: 0.6.1
# 当前激活的配置名称(请不要修改)
profile: dev
# MySQL数据库连接地址
dburl: jdbc:mysql://192.168.9.191:3306/platon_browser_${version}_${profile}?useUnicode=true&characterEncoding=utf-8&useSSL=false
# MySQL数据库用户名
dbuser: platon
# MySQL数据库密码
dbpass: platon
web3j:
  addresses: http://10.10.8.200:6789,http://10.10.8.201:6789,http://10.10.8.202:6789,http://10.10.8.203:6789
  collect.batch-size: 5
# Redis集群节点
redis: 192.168.9.191:7001,192.168.9.191:7002,192.168.9.191:7003,192.168.9.191:7004,192.168.9.191:7005,192.168.9.191:7006
# 日志文件存储文件
logpath: ./logs/${spring.application.name}-${version}-${profile}.log
# 日志级别
loglevel:
  spring: debug
  platon: debug
  platon.job: debug
  platon.filter: debug
  platon.service: debug
  platon.thread: debug
# 区块分析线程池大小
thread.num: 500
# 区块批量采集大小
batch.num: ${thread.num}
