# ***************************开发配置**************************** #
spring:
  redis:
    cluster:
      max-redirects: 3
      nodes: 192.168.16.171:7001,192.168.16.171:7002,192.168.16.171:7000,192.168.16.172:7000,192.168.16.172:7001,192.168.16.172:7002
    password: platscan

# 应用版本
version: 0.7.0
# 当前激活的配置名称(请不要修改)
profile: test
# MySQL数据库连接地址
dburl: jdbc:mysql://192.168.16.171:3306/platon_browser_${version}_${profile}?useUnicode=true&characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
# MySQL数据库用户名
dbuser: ENC(WdsbLfMqOVt4fifwvlrP/g==)
# MySQL数据库密码
dbpass: ENC(YAS0fQLf2HgpNwy8EosToc3pBFUyvsla)
web3j:
  addresses: http://192.168.112.171:6789,http://192.168.112.171:7789,http://192.168.112.172:6789,http://192.168.112.172:7789
  collect.batch-size: 1000
#日志配置
logging:
  file: ./logs/${spring.application.name}-${version}-${profile}.log
  level:
    org.springframework: debug
    com.platon.browser: debug
    com.platon.browser.service: debug
    com.platon.browser.task: debug
    com.platon.browser.client: debug
    com.platon.browser.dao: debug
    com.platon.browser.engine: debug
    com.platon.browser.engine.handler.epoch: error

#初始化链相关的配置
platon.config:
  # 质押节点统计年化率最多取多少个连续周期
  maxSettlePeriodCount4AnnualizedRateStat: 4
  #PlatON初始总发行量(LAT)
  initIssueAmount: 10000000000
  #每年固定增发比例
  addIssueRate: 0.025
  #每年增发分配给激励池的比例
  incentiveRateFromIssue: 0.8
  #每个共识轮中回退多少个块是选举下一轮验证人的时机
  electionBackwardBlockCount: 20
  #开发者激励基金账户地址
  developerIncentiveFundAccountAddr: '0x60ceca9c1290ee56b98d4e160ef0453f7c40d219'
  #PlatOn基金会账户地址
  platonFundAccountAddr: '0x493301712671ada506ba6ca7891f436d29185821'
  #10年内基金会向激励池填充额度: <第几年-补贴金额(LAT)>
  foundationSubsidies: {
    '1':62215742.4869165,
    '2':55965742.4869165,
    '3':49559492.4869165,
    '4':42993086.2369165,
    '5':36262519.8306666,
    '6':29363689.2642633,
    '7':22292387.9336939,
    '8':15044304.0698633,
    '9':7615018.1094369
  }
  # 初始内置节点默认质押金额(LAT)
  defaultStakingLockedAmount: 10000000
  #提案url参数模板
  proposalUrlTemplate: https://github.com/danielgogo/PIPs/blob/master/PIP-{pip_id}.md
  #keysBase网址
  keyBase: https://keybase.io/
