# ***************************开发配置**************************** #
#服务器配置
server.port: 9040
#Spring应用配置
spring.redis.cluster.nodes: 192.168.18.9:21006,192.168.18.9:21007,192.168.18.9:21008,192.168.18.9:21009,192.168.18.9:21010,192.168.18.9:21011
#数据源配置
datasource:
  url: jdbc:mysql://192.168.9.191:3306/platon_browser_0.4.0_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false
  username: platon
  password: platon

#日志配置
logging:
  file: ./browser-agent-dev-1.log
  level:
    org:
      springframework:
        boot: debug
        web: debug
        jdbc: debug
        dao: debug
        transaction: debug
      mybatis: debug
    com.platon.browser.dao: debug
#Elastic job日志存储位置
log.eljob.path: ./logs

platon:
  # 链配置格式 [chainName]-[chainId]-[http://nodeIP:port]，多个链配置使用逗号分隔
  chains: MAIN_NET-1-http://192.168.9.76:8793
  # 区块列表缓存和交易列表缓存配置
  redis:
    key:
      node: browser:0.4.0:dev:chain{}:nodes
      push-node: browser:0.4.0:dev:chain{}:pushnodes
      block: browser:0.4.0:dev:chain{}:blocks
      transaction: browser:0.4.0:dev:chain{}:transactions
      maxtps: browser:0.4.0:dev:chain{}:maxtps
      max-item: 500000
      number: browser:0.4.0:dev:chain{}:number
      staticstics: browser:0.4.0:dev:chain{}:staticstics
  # 图片服务器地址
  image.server.url: http://192.168.9.86:8082/

#Web3j配置
node.ip: http://192.168.9.76:8793
chain.id: 1
# Zookeeper注册中心配置
regCenter:
  serverList: 192.168.9.191:2181
  namespace: browser_job_0.4.0