# ***************************通用配置**************************** #
# 应用版本
version: 0.4.2
#服务器配置
server:
  port: ${port}
  context-path: /browser-agent
#Spring应用配置
spring:
  profiles.active: dev
  application.name: browser-agent
  #Redis集群配置
  redis:
    database: 0
    cluster:
      max-redirects: 3
      nodes: ${redis}
#数据源配置
datasource:
  url: ${dburl}
  username: ${dbuser}
  password: ${dbpass}
  driverClassName: com.mysql.jdbc.Driver
# Platon配置
platon:
  chain:
    config: ${chain.config}
    active: ${chain.active}
  # 虚假节点位置配置文件
  fake.location.filename: fakelocation.json
  # 批量采集线程池大小
  block.pool.size: ${thread.num}
  # 批量处理数量
  block.batch.num: ${batch.num}
  # 区块列表缓存和交易列表缓存配置
  redis:
    key:
      node: browser:${version}:${profile}:chain{}:nodes
      block: browser:${version}:${profile}:chain{}:blocks
      transaction: browser:${version}:${profile}:chain{}:transactions
      staticstics: browser:${version}:${profile}:chain{}:staticstics
    max-item: 500000
#日志配置
logging:
  file: ${logpath}
  level:
    org.springframework: ${loglevel.spring}
    com.platon.browser: ${loglevel.platon}
    com.platon.browser.job: ${loglevel.platon.job}
    com.platon.browser.filter: ${loglevel.platon.filter}
