# ***************************开发配置**************************** #
#服务器配置
server.port: 9030
#Spring应用配置
spring.redis.cluster.nodes: 10.0.0.8:21006,10.0.0.8:21007,10.0.0.8:21008,10.0.0.8:21009,10.0.0.8:21010,10.0.0.8:21011
#数据源配置
datasource:
  url: jdbc:mysql://52.187.38.88:3306/platon_browser_0.3.0?useUnicode=true&characterEncoding=utf-8&useSSL=false
  username: root
  password: Juzhenyuan_123
#日志配置
logging:
  file: /data/logs/browser-agent-prod.log
  level:
    org:
      springframework:
        boot: error
        web: error
        jdbc: error
        dao: error
        transaction: error
      mybatis: error
    com.platon.browser.dao: error
    com.platon.browser.job: ${debug.level.job}
    com.platon.browser.filter: ${debug.level.filter}
#Elastic job日志存储位置
log.eljob.path: ./logs

platon:
  # 链配置格式 [chainName]-[chainId]-[http://nodeIP:port]，多个链配置使用逗号分隔
  chains: MAIN_NET-1-http://10.0.0.5:6790
  # 批量采集线程池大小
  block.pool.size: ${thread.num}
  # 批量处理数量
  block.batch.num: ${batch.num}
  # 区块列表缓存和交易列表缓存配置
  redis:
    key:
      node: browser:prod:chain{}:nodes
      block: browser:prod:chain{}:blocks
      transaction: browser:prod:chain{}:transactions
      staticstics: browser:prod:chain{}:staticstics
      max-item: 500000
#Web3j配置
chain.id: 1
# Zookeeper注册中心配置
regCenter:
  serverList: 10.0.0.8:2181
  namespace: browser_job_0.4.0
