# ***************************开发配置**************************** #
# 当前激活的配置名称(请不要修改)
profile: test
# 服务器端口号
port: 9042
# MySQL数据库连接地址
dburl: jdbc:mysql://54.252.202.130:3306/platon_browser_${version}_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
# MySQL数据库用户名
dbuser: juzix
# MySQL数据库密码
dbpass: Juzhen123!
chain:
  # Platon链配置,格式【{chainName1}-{chainId1}-{http://nodeIP1:port1}[,{chainName2}-{chainId2}-{http://nodeIP2:port2}]】，多个链配置使用逗号分隔
  config: MAIN_NET-1-http://54.252.202.130:6789
  # 要采集哪个ID的链
  active: 1
# Redis集群节点
#redis: 192.168.18.9:21006,192.168.18.9:21007,192.168.18.9:21008,192.168.18.9:21009,192.168.18.9:21010,192.168.18.9:21011
redis: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005,127.0.0.1:7006
# 日志文件存储文件
logpath: ./logs/browser-agent-${version}-${profile}.log
# 日志级别
loglevel:
  spring: error
  platon: error
  platon.job: error
  platon.filter: error
# 区块分析线程池大小
thread.num: 200
# 区块批量采集大小
batch.num: ${thread.num}