# ***************************通用配置**************************** #
#服务器配置
server.context-path: /browser-agent
#Spring应用配置
spring:
  profiles.active: prod
  application.name: browser-agent
  #Redis集群配置
  redis:
    database: 0
    cluster.max-redirects: 3
#数据源配置
datasource.driverClassName: com.mysql.jdbc.Driver
jdbc.validationQuery: SELECT 1
#Web3j配置
node.type: eth
netInfo: v0.4.0
# 默认区块处理线程数量
thread.num: 50